# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBaidui():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_baidui(self):
    self.driver.get("https://www.baidu.com/")
    self.driver.set_window_size(1936, 1056)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win6340"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.find_element(By.ID, "header_blk").click()
    self.driver.find_element(By.LINK_TEXT, "关于我们").click()
    self.driver.find_element(By.LINK_TEXT, "公司简介").click()
    self.driver.find_element(By.ID, "main").click()
    self.driver.find_element(By.ID, "main").click()
  
